2020-10-05 08:17:32,385 p=26372 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-05 08:17:32,399 p=26372 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-05 08:17:34,900 p=26372 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-05 08:17:34,903 p=26372 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-05 08:17:34,927 p=26372 u=ansible n=ansible | TASK [aide check] ****************************************************************************************************************************
2020-10-05 08:18:27,138 p=26372 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-05 08:18:27,141 p=26372 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-05 08:18:27,142 p=26372 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-05 09:20:04,952 p=27084 u=ansible n=ansible | ERROR! unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>

The error appears to be in '/home/ansible/ansible/tasks/bootpermission.yml': line 5, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: grub_cfg permission
             ^ here

2020-10-05 09:21:44,331 p=27227 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-05 09:21:44,340 p=27227 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-05 09:21:45,698 p=27227 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-05 09:21:45,699 p=27227 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-05 09:21:45,710 p=27227 u=ansible n=ansible | TASK [grub_cfg permission] *******************************************************************************************************************
2020-10-05 09:21:46,215 p=27227 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-05 09:21:46,228 p=27227 u=ansible n=ansible | TASK [grubenv premission] ********************************************************************************************************************
2020-10-05 09:21:46,540 p=27227 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-05 09:21:46,543 p=27227 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-05 09:21:46,543 p=27227 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-08 07:39:14,349 p=23412 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 07:39:14,368 p=23412 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 07:39:16,109 p=23412 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 07:39:16,109 p=23412 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:39:16,121 p=23412 u=ansible n=ansible | TASK [list security updates] *****************************************************************************************************************
2020-10-08 07:39:17,717 p=23412 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:39:17,730 p=23412 u=ansible n=ansible | TASK [debug] *********************************************************************************************************************************
2020-10-08 07:39:17,746 p=23412 u=ansible n=ansible | skipping: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:39:17,757 p=23412 u=ansible n=ansible | TASK [install security updates] **************************************************************************************************************
2020-10-08 07:39:24,108 p=23412 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:39:24,112 p=23412 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 07:39:24,112 p=23412 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
2020-10-08 07:48:34,980 p=23881 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 07:48:34,988 p=23881 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 07:48:36,351 p=23881 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 07:48:36,351 p=23881 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:48:36,363 p=23881 u=ansible n=ansible | TASK [chrony installed] **********************************************************************************************************************
2020-10-08 07:48:37,652 p=23881 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:48:37,665 p=23881 u=ansible n=ansible | TASK [chrony start] **************************************************************************************************************************
2020-10-08 07:48:38,545 p=23881 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Could not find the requested service chrony: host"}
2020-10-08 07:48:38,548 p=23881 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 07:48:38,548 p=23881 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-08 07:49:20,464 p=24370 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 07:49:20,472 p=24370 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 07:49:21,617 p=24370 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 07:49:21,617 p=24370 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:49:21,629 p=24370 u=ansible n=ansible | TASK [chrony installed] **********************************************************************************************************************
2020-10-08 07:49:22,978 p=24370 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:49:22,992 p=24370 u=ansible n=ansible | TASK [chrony start] **************************************************************************************************************************
2020-10-08 07:49:23,877 p=24370 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:49:23,880 p=24370 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 07:49:23,881 p=24370 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-08 07:51:49,474 p=24717 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 07:51:49,482 p=24717 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 07:51:50,814 p=24717 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 07:51:50,814 p=24717 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:51:50,826 p=24717 u=ansible n=ansible | TASK [chrony installed] **********************************************************************************************************************
2020-10-08 07:51:52,067 p=24717 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:51:52,081 p=24717 u=ansible n=ansible | TASK [chrony start] **************************************************************************************************************************
2020-10-08 07:51:52,912 p=24717 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 07:51:52,925 p=24717 u=ansible n=ansible | TASK [change timezone] ***********************************************************************************************************************
2020-10-08 14:21:53,480 p=24717 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:21:53,483 p=24717 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 14:21:53,484 p=24717 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-08 14:29:55,560 p=25227 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 14:29:55,568 p=25227 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 14:29:56,370 p=25227 u=ansible n=ansible |  [ERROR]: User interrupted execution

2020-10-08 14:30:00,669 p=25350 u=ansible n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: No JSON object could be decoded

Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to be in '/home/ansible/ansible/tasks/gui.yml': line 11, column 29, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

             yum:
                     name: {{result}}
                            ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-08 14:30:25,602 p=25403 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 14:30:25,610 p=25403 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 14:30:26,750 p=25403 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 14:30:26,751 p=25403 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:30:26,762 p=25403 u=ansible n=ansible | TASK [list xorg-x11*] ************************************************************************************************************************
2020-10-08 14:30:28,446 p=25403 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:30:28,460 p=25403 u=ansible n=ansible | TASK [remove xorg-x11] ***********************************************************************************************************************
2020-10-08 14:30:29,495 p=25403 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:30:29,498 p=25403 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 14:30:29,499 p=25403 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-08 14:31:28,014 p=25739 u=ansible n=ansible | ERROR! conflicting action statements: msg, yum

The error appears to be in '/home/ansible/ansible/tasks/gui.yml': line 5, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: list xorg-x11*
             ^ here

2020-10-08 14:32:39,810 p=25749 u=ansible n=ansible | ERROR! conflicting action statements: debug, yum

The error appears to be in '/home/ansible/ansible/tasks/gui.yml': line 5, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: list xorg-x11*
             ^ here

2020-10-08 14:33:31,258 p=25756 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 14:33:31,266 p=25756 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 14:33:32,621 p=25756 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 14:33:32,621 p=25756 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:33:32,633 p=25756 u=ansible n=ansible | TASK [list xorg-x11*] ************************************************************************************************************************
2020-10-08 14:33:34,185 p=25756 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:33:34,199 p=25756 u=ansible n=ansible | TASK [list all] ******************************************************************************************************************************
2020-10-08 14:33:34,230 p=26028 u=ansible n=ansible | [WARNING]: Using a variable for a task's 'args' is unsafe in some situations (see
https://docs.ansible.com/ansible/devel/reference_appendices/faq.html#argsplat-unsafe)

2020-10-08 14:33:34,236 p=25756 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"msg": "Invalid options for debug: failed,changed,results"}
2020-10-08 14:33:34,238 p=25756 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 14:33:34,238 p=25756 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-08 14:33:45,286 p=26032 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 14:33:45,294 p=26032 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 14:33:46,422 p=26032 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 14:33:46,422 p=26032 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:33:46,434 p=26032 u=ansible n=ansible | TASK [list xorg-x11*] ************************************************************************************************************************
2020-10-08 14:33:46,665 p=26032 u=ansible n=ansible |  [ERROR]: User interrupted execution

2020-10-08 14:34:08,708 p=26179 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 14:34:08,716 p=26179 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 14:34:09,876 p=26179 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 14:34:09,877 p=26179 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:34:09,889 p=26179 u=ansible n=ansible | TASK [list xorg-x11*] ************************************************************************************************************************
2020-10-08 14:34:11,647 p=26179 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:34:11,661 p=26179 u=ansible n=ansible | TASK [list all] ******************************************************************************************************************************
2020-10-08 14:34:11,699 p=26179 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": {
        "changed": false, 
        "failed": false, 
        "results": []
    }
}
2020-10-08 14:34:11,711 p=26179 u=ansible n=ansible | TASK [remove xorg-x11] ***********************************************************************************************************************
2020-10-08 14:34:12,774 p=26179 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 14:34:12,778 p=26179 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 14:34:12,778 p=26179 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-08 20:40:34,349 p=28378 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 20:40:34,357 p=28378 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 20:40:35,718 p=28378 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 20:40:35,718 p=28378 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 20:40:35,730 p=28378 u=ansible n=ansible | TASK [list xorg-x11*] ************************************************************************************************************************
2020-10-08 20:40:37,350 p=28378 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 20:40:37,364 p=28378 u=ansible n=ansible | TASK [remove xorg-x11] ***********************************************************************************************************************
2020-10-08 20:40:38,436 p=28378 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 20:40:38,440 p=28378 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 20:40:38,440 p=28378 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-08 21:30:27,099 p=29416 u=ansible n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: No JSON object could be decoded

Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to be in '/home/ansible/ansible/tasks/service_disable_input.yml': line 9, column 21, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: {{ taskname }}
                    ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-08 21:30:50,863 p=29446 u=ansible n=ansible | ERROR! conflicting action statements: state, enabled

The error appears to be in '/home/ansible/ansible/tasks/service_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: '{{ taskname }}'
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-08 21:33:18,885 p=29544 u=ansible n=ansible | ERROR! A malformed block was encountered while loading tasks: {u'service': {u'state': u'stop', u'enabled': False, u'name': u'{{ taskname }}'}} should be a list or None but is <class 'ansible.parsing.yaml.objects.AnsibleMapping'>

The error appears to be in '/home/ansible/ansible/tasks/service_disable_input.yml': line 2, column 4, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
 - hosts: control
   ^ here

2020-10-08 21:35:17,063 p=29610 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 21:35:17,071 p=29610 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 21:35:18,426 p=29610 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 21:35:18,426 p=29610 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 21:35:18,438 p=29610 u=ansible n=ansible | TASK [disable service] ***********************************************************************************************************************
2020-10-08 21:35:19,304 p=29610 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "value of state must be one of: reloaded, restarted, started, stopped, got: stop"}
2020-10-08 21:35:19,307 p=29610 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 21:35:19,307 p=29610 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-08 21:35:45,818 p=29923 u=ansible n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: No JSON object could be decoded

Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to be in '/home/ansible/ansible/tasks/service_disable_input.yml': line 11, column 22, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

             service:
              name: {{ taskname }}
                     ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-08 21:36:43,222 p=29931 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 21:36:43,231 p=29931 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 21:36:44,574 p=29931 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 21:36:44,574 p=29931 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 21:36:44,586 p=29931 u=ansible n=ansible | TASK [disable service] ***********************************************************************************************************************
2020-10-08 21:36:45,468 p=29931 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "value of state must be one of: reloaded, restarted, started, stopped, got: stop"}
2020-10-08 21:36:45,471 p=29931 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 21:36:45,471 p=29931 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-08 21:37:06,649 p=30202 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 21:37:06,657 p=30202 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 21:37:07,816 p=30202 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 21:37:07,817 p=30202 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 21:37:07,829 p=30202 u=ansible n=ansible | TASK [disable service] ***********************************************************************************************************************
2020-10-08 21:37:08,929 p=30202 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 21:37:08,933 p=30202 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 21:37:08,933 p=30202 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-08 21:42:47,429 p=30558 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-08 21:42:47,437 p=30558 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-08 21:42:48,789 p=30558 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-08 21:42:48,790 p=30558 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 21:42:48,802 p=30558 u=ansible n=ansible | TASK [remove NIS] ****************************************************************************************************************************
2020-10-08 21:42:50,072 p=30558 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-08 21:42:50,075 p=30558 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-08 21:42:50,075 p=30558 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:40:51,227 p=8034 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:40:51,235 p=8034 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:40:52,553 p=8034 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:40:52,553 p=8034 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:40:52,564 p=8034 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:40:53,056 p=8034 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:40:53,059 p=8034 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:40:53,059 p=8034 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:41:51,076 p=8321 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:41:51,084 p=8321 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:41:52,194 p=8321 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:41:52,194 p=8321 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:41:52,206 p=8321 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:41:52,769 p=8321 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:41:52,773 p=8321 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:41:52,773 p=8321 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:42:21,869 p=8561 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:42:21,877 p=8561 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:42:22,956 p=8561 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:42:22,956 p=8561 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:42:22,968 p=8561 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:42:23,513 p=8561 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:42:23,516 p=8561 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:42:23,516 p=8561 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:46:48,736 p=8804 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:46:48,744 p=8804 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:46:50,058 p=8804 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:46:50,058 p=8804 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:46:50,070 p=8804 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:46:50,548 p=8804 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:46:50,552 p=8804 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:46:50,552 p=8804 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:47:05,417 p=9121 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:47:05,425 p=9121 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:47:06,512 p=9121 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:47:06,513 p=9121 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:47:06,524 p=9121 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:47:07,072 p=9121 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:47:07,075 p=9121 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:47:07,076 p=9121 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:47:12,917 p=9355 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:47:12,925 p=9355 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:47:14,005 p=9355 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:47:14,005 p=9355 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:47:14,017 p=9355 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:47:14,565 p=9355 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:47:14,568 p=9355 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:47:14,568 p=9355 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:49:59,104 p=9656 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:49:59,111 p=9656 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:50:00,422 p=9656 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:50:00,422 p=9656 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:50:00,434 p=9656 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:50:00,911 p=9656 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sysctl) module: register Supported parameters include: ignoreerrors, name, reload, state, sysctl_file, sysctl_set, value"}
2020-10-10 12:50:00,914 p=9656 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:50:00,914 p=9656 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-10 12:50:59,314 p=9934 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:50:59,322 p=9934 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:51:00,436 p=9934 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:51:00,436 p=9934 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:51:00,448 p=9934 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:51:00,985 p=9934 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sysctl) module: register Supported parameters include: ignoreerrors, name, reload, state, sysctl_file, sysctl_set, value"}
2020-10-10 12:51:00,987 p=9934 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:51:00,987 p=9934 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-10 12:51:35,967 p=10166 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:51:35,975 p=10166 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:51:37,055 p=10166 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:51:37,056 p=10166 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:51:37,067 p=10166 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:51:37,611 p=10166 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sysctl) module: register Supported parameters include: ignoreerrors, name, reload, state, sysctl_file, sysctl_set, value"}
2020-10-10 12:51:37,614 p=10166 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:51:37,614 p=10166 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-10 12:52:37,798 p=10398 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:52:37,806 p=10398 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:52:39,077 p=10398 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:52:39,077 p=10398 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:52:39,088 p=10398 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:52:39,566 p=10398 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:52:39,579 p=10398 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 12:52:39,615 p=10398 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': False}"
    ]
}
2020-10-10 12:52:39,617 p=10398 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:52:39,618 p=10398 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:53:08,441 p=10676 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:53:08,449 p=10676 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:53:09,526 p=10676 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:53:09,526 p=10676 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:53:09,538 p=10676 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:53:10,081 p=10676 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:53:10,093 p=10676 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 12:53:10,130 p=10676 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': False}"
    ]
}
2020-10-10 12:53:10,133 p=10676 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:53:10,133 p=10676 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:57:16,082 p=10915 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:57:16,090 p=10915 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:57:17,374 p=10915 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:57:17,375 p=10915 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:57:17,386 p=10915 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:57:17,865 p=10915 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:57:17,877 p=10915 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 12:57:17,913 p=10915 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': False}"
    ]
}
2020-10-10 12:57:17,915 p=10915 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:57:17,915 p=10915 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 12:59:34,801 p=3450 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 12:59:34,814 p=3450 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 12:59:36,191 p=3450 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 12:59:36,191 p=3450 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:59:36,203 p=3450 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 12:59:36,699 p=3450 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 12:59:36,712 p=3450 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 12:59:36,765 p=3450 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': False}"
    ]
}
2020-10-10 12:59:36,767 p=3450 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 12:59:36,768 p=3450 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 13:00:47,939 p=3744 u=ansible n=ansible |   hosts (1):
2020-10-10 13:00:47,939 p=3744 u=ansible n=ansible |     ip-192-168-1-34.ap-southeast-1.compute.internal
2020-10-10 13:00:52,681 p=3748 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:00:52,689 p=3748 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:00:53,998 p=3748 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:00:53,998 p=3748 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:00:54,010 p=3748 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 13:00:54,496 p=3748 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:00:54,509 p=3748 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 13:00:54,546 p=3748 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': False}"
    ]
}
2020-10-10 13:00:54,548 p=3748 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:00:54,548 p=3748 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 13:03:42,627 p=4089 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:03:42,635 p=4089 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:03:43,911 p=4089 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:03:43,911 p=4089 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:03:43,923 p=4089 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 13:03:44,417 p=4089 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:03:44,430 p=4089 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 13:03:44,466 p=4089 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': True}"
    ]
}
2020-10-10 13:03:44,468 p=4089 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:03:44,469 p=4089 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 13:03:58,212 p=4369 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:03:58,219 p=4369 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:03:59,286 p=4369 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:03:59,286 p=4369 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:03:59,298 p=4369 u=ansible n=ansible | TASK [ip forward disable] ********************************************************************************************************************
2020-10-10 13:03:59,851 p=4369 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:03:59,864 p=4369 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 13:03:59,900 p=4369 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': True}"
    ]
}
2020-10-10 13:03:59,902 p=4369 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:03:59,902 p=4369 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 13:05:43,788 p=4630 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:05:43,796 p=4630 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:05:45,085 p=4630 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:05:45,085 p=4630 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:05:45,097 p=4630 u=ansible n=ansible | TASK [packet redirects disable] **************************************************************************************************************
2020-10-10 13:05:45,588 p=4630 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:05:45,601 p=4630 u=ansible n=ansible | TASK [output] ********************************************************************************************************************************
2020-10-10 13:05:45,636 p=4630 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal] => {
    "msg": [
        " {'failed': False, u'changed': True}"
    ]
}
2020-10-10 13:05:45,639 p=4630 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:05:45,639 p=4630 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 13:18:39,648 p=5052 u=ansible n=ansible | ERROR! 'var_prompt' is not a valid attribute for a Play

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 2, column 4, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
 - hosts: control
   ^ here

2020-10-10 13:19:25,848 p=5074 u=ansible n=ansible | ERROR! couldn't resolve module/action 'systclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: disable '{{ taskname }}'
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-10 13:20:19,066 p=5088 u=ansible n=ansible | ERROR! couldn't resolve module/action 'systclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: disable
             ^ here

2020-10-10 13:20:47,144 p=5098 u=ansible n=ansible | ERROR! couldn't resolve module/action 'sysclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: disable "{{taskname}}"
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-10 13:22:02,857 p=5105 u=ansible n=ansible | ERROR! couldn't resolve module/action 'sysclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: disable "{{ taskname }}"
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-10 13:23:41,622 p=5123 u=ansible n=ansible | ERROR! couldn't resolve module/action 'sysclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: disable "{{taskname}}"
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-10 13:24:32,797 p=5130 u=ansible n=ansible | ERROR! couldn't resolve module/action 'sysclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: 'disable "{{taskname}}"'
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-10 13:25:30,462 p=5136 u=ansible n=ansible | ERROR! couldn't resolve module/action 'sysclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - name: 'disable "{{taskname}}"'
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-10 13:25:41,308 p=5186 u=ansible n=ansible | ERROR! couldn't resolve module/action 'sysclt'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/ansible/tasks/network_disable_input.yml': line 9, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
           - sysclt:
             ^ here

2020-10-10 13:29:31,840 p=5195 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:29:31,848 p=5195 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:29:33,179 p=5195 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:29:33,180 p=5195 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:29:33,207 p=5195 u=ansible n=ansible | TASK [net.ipv4.conf.all.accept_source_route] *************************************************************************************************
2020-10-10 13:29:33,706 p=5195 u=ansible n=ansible | [WARNING]: The value 0 (type int) in a string field was converted to u'0' (type string). If this does not look like what you expect, quote
the entire value to ensure it does not change.

2020-10-10 13:29:33,706 p=5195 u=ansible n=ansible | changed: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:29:33,709 p=5195 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:29:33,709 p=5195 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 13:31:24,668 p=5488 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:31:24,676 p=5488 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:31:25,975 p=5488 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:31:25,975 p=5488 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:31:26,002 p=5488 u=ansible n=ansible | TASK [sysctl net.ipv4.conf.all.accept_source_route] ******************************************************************************************
2020-10-10 13:31:26,499 p=5488 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: net.ipv4.ip_forward = 0\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.conf.all.accept_source_route = 0\nsysctl: cannot stat /proc/sys/sysctl net/ipv4/conf/all/accept_source_route: No such file or directory\n"}
2020-10-10 13:31:26,502 p=5488 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:31:26,502 p=5488 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-10 13:31:58,428 p=5763 u=ansible n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: No JSON object could be decoded

Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to be in '/home/ansible/ansible/tasks/network_disable.yml': line 15, column 30, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

                     name: "{{ network }}"
                     value: {{ value }}
                             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2020-10-10 13:32:21,287 p=5769 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:32:21,295 p=5769 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:32:22,384 p=5769 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:32:22,385 p=5769 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:32:22,435 p=5769 u=ansible n=ansible | TASK [sysctl net.ipv4.conf.all.accept_source_route] ******************************************************************************************
2020-10-10 13:32:22,924 p=5769 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: net.ipv4.ip_forward = 0\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.conf.all.accept_source_route = 0\nsysctl: cannot stat /proc/sys/sysctl net/ipv4/conf/all/accept_source_route: No such file or directory\n"}
2020-10-10 13:32:22,927 p=5769 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:32:22,927 p=5769 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-10 13:34:16,733 p=6007 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:34:16,741 p=6007 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:34:18,050 p=6007 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:34:18,051 p=6007 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:34:18,078 p=6007 u=ansible n=ansible | TASK [net.ipv4.conf.all.accept_source_route] *************************************************************************************************
2020-10-10 13:34:18,573 p=6007 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: net.ipv4.ip_forward = 0\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.conf.all.accept_source_route = 1\nsysctl: cannot stat /proc/sys/sysctl net/ipv4/conf/all/accept_source_route: No such file or directory\n"}
2020-10-10 13:34:18,576 p=6007 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:34:18,576 p=6007 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-10 13:35:09,939 p=6283 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:35:09,947 p=6283 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:35:11,047 p=6283 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:35:11,047 p=6283 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:35:11,103 p=6283 u=ansible n=ansible | TASK [net.ipv4.conf.all.accept_source_route] *************************************************************************************************
2020-10-10 13:35:11,608 p=6283 u=ansible n=ansible | [WARNING]: The value 0 (type int) in a string field was converted to u'0' (type string). If this does not look like what you expect, quote
the entire value to ensure it does not change.

2020-10-10 13:35:11,608 p=6283 u=ansible n=ansible | fatal: [ip-192-168-1-34.ap-southeast-1.compute.internal]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: net.ipv4.ip_forward = 0\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.conf.all.accept_source_route = 0\nsysctl: cannot stat /proc/sys/sysctl net/ipv4/conf/all/accept_source_route: No such file or directory\n"}
2020-10-10 13:35:11,611 p=6283 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:35:11,611 p=6283 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-10-10 13:35:35,150 p=6519 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:35:35,158 p=6519 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:35:36,235 p=6519 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:35:36,235 p=6519 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:35:36,287 p=6519 u=ansible n=ansible | TASK [net.ipv4.conf.all.send_redirects] ******************************************************************************************************
2020-10-10 13:35:36,763 p=6519 u=ansible n=ansible | [WARNING]: The value 0 (type int) in a string field was converted to u'0' (type string). If this does not look like what you expect, quote
the entire value to ensure it does not change.

2020-10-10 13:35:36,763 p=6519 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:35:36,766 p=6519 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:35:36,766 p=6519 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-10-10 13:36:44,686 p=6758 u=ansible n=ansible | PLAY [control] *******************************************************************************************************************************
2020-10-10 13:36:44,694 p=6758 u=ansible n=ansible | TASK [Gathering Facts] ***********************************************************************************************************************
2020-10-10 13:36:46,024 p=6758 u=ansible n=ansible | [WARNING]: Platform linux on host ip-192-168-1-34.ap-southeast-1.compute.internal is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

2020-10-10 13:36:46,024 p=6758 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:36:46,051 p=6758 u=ansible n=ansible | TASK [net.ipv4.conf.all.send_redirects] ******************************************************************************************************
2020-10-10 13:36:46,544 p=6758 u=ansible n=ansible | ok: [ip-192-168-1-34.ap-southeast-1.compute.internal]
2020-10-10 13:36:46,548 p=6758 u=ansible n=ansible | PLAY RECAP ***********************************************************************************************************************************
2020-10-10 13:36:46,548 p=6758 u=ansible n=ansible | ip-192-168-1-34.ap-southeast-1.compute.internal : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
